# Default values for kafka-connect.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass
##

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##

global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## @param image.registry Kafka connect image registry
## @param image.repository Kafka connect image repository
## @param image.tag Kafka connect image tag (immutable tags are recommended)
## @param image.pullPolicy image pull policy
## @param image.pullSecrets Kafka connect image pull secrets
##
image:
  registry: docker.io
  repository: confluentinc/cp-kafka-connect
  tag: 6.1.0
  ## Specify a imagePullPolicy
  ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ## e.g:
  ## pullSecrets:
  ##   - myRegistryKeySecretName
  ##
  pullSecrets: []

## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects (sub-charts are not considered)
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}

## @param replicaCount to decide the number of kafka connect pod replicas
##
replicaCount: 1

## @param extraEnvVars Extra environment variables to be set on kafka connect container
## For example:
##  - name: FOO
##    value: BAR
##
extraEnvVars: []

service:
  ## @param service.type Kafka connect service type
  ##
  type: ClusterIP
  ## @param service.ports.kafkaConnect Kafka connect service Port
  ## @param service.ports.jmx jmx Port
  ports:
    kafkaConnect: 8083
    jmx: 5556

  ## @param service.extraPorts Extra ports to expose in the service (normally used with the `sidecar` value)
  ##
  extraPorts: []
  ## @param service.loadBalancerIP LoadBalancerIP if service type is `LoadBalancer`
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  loadBalancerIP: ""
  ## @param service.loadBalancerSourceRanges Service Load Balancer sources
  ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ## e.g:
  ## loadBalancerSourceRanges:
  ##   - 10.10.10.0/24
  ##
  loadBalancerSourceRanges: []
  ## @param service.clusterIP Service Cluster IP
  ## e.g.:
  ## clusterIP: None
  ##
  clusterIP: ""
  ## @param service.externalTrafficPolicy Service external traffic policy
  ## ref https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster
  ## @param service.annotations Provide any additional annotations which may be required.
  ## This can be used to set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  annotations: {}
  ## @param service.sessionAffinity Session Affinity for Kubernetes service, can be "None" or "ClientIP"
  ## If "ClientIP", consecutive client requests will be directed to the same Pod
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies
  ##
  sessionAffinity: None
  ## @param service.sessionAffinityConfig Additional settings for the sessionAffinity
  ## sessionAffinityConfig:
  ##   clientIP:
  ##     timeoutSeconds: 300
  ##
  sessionAffinityConfig: {}

##The Kafka Connect properties
## ref: https://docs.confluent.io/current/connect/userguide.html#configuring-workers
configurationOverrides:
  ##  @param configurationOverrides.plugin.path the plugin path in the file system
  "plugin.path": "/usr/share/java,/usr/share/confluent-hub-components"
  ##  @param configurationOverrides.key.converter the serializer for keys
  "key.converter": "io.confluent.connect.avro.AvroConverter"
  ##  @param configurationOverrides.value.converter the serializer for values
  "value.converter": "io.confluent.connect.avro.AvroConverter"
  ##  @param configurationOverrides.key.converter.schemas.enable enable schemas for key converter
  "key.converter.schemas.enable": "false"
  ##  @param configurationOverrides.value.converter.schemas.enable enable schemas for value converter
  "value.converter.schemas.enable": "false"
  ##  @param configurationOverrides.internal.key.converter internal key converter
  "internal.key.converter": "org.apache.kafka.connect.json.JsonConverter"
  ##  @param configurationOverrides.internal.value.converter internal value converter
  "internal.value.converter": "org.apache.kafka.connect.json.JsonConverter"
  ##  @param configurationOverrides.config.storage.replication.factor config storage replication factor
  "config.storage.replication.factor": "3"
  ##  @param configurationOverrides.offset.storage.replication.factor offset storage replication factor
  "offset.storage.replication.factor": "3"
  ##  @param configurationOverrides.status.storage.replication.factor status storage replication factor
  "status.storage.replication.factor": "3"

## @param heapOptions Kafka Connect JVM Heap Option
heapOptions: "-Xms512M -Xmx512M"

## Additional env variables
## @param customEnv Additional env variables
customEnv: {}

## @param resources The limits and requests for kafka connect containers
resources: {}
  # We recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

## @param podAnnotations Custom pod annotations
podAnnotations: {}

## @param nodeSelector Node labels for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

## @param tolerations Taints to tolerate on node assignment:
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## @param affinity Pod scheduling constraints
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## @param jmx.port Kafka Connect JMX Settings for Monitoring
## ref: https://kafka.apache.org/documentation/#connect_monitoring
jmx:
  port: 5555

## Prometheus Exporter Configuration
## ref: https://prometheus.io/docs/instrumenting/exporters/
prometheus:
  ## JMX Exporter Configuration
  ## ref: https://github.com/prometheus/jmx_exporter
  jmx:
    ## @param prometheus.jmx.enabled JMX Exporter
    enabled: true

    ## @param prometheus.jmx.image.registry JMX Exporter image registry
    ## @param prometheus.jmx.image.repository JMX Exporter image repository
    ## @param prometheus.jmx.image.tag JMX Exporter image tag
    ## @param prometheus.jmx.image.pullPolicy JMX Exporter image pull policy
    ## @param prometheus.jmx.image.pullSecrets JMX Exporter image pull secrets
    image:
      registry: docker.io
      repository: solsson/kafka-prometheus-jmx-exporter@sha256
      tag: 6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143
      ## Specify a imagePullPolicy
      ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
      ##
      pullPolicy: IfNotPresent
      ## Optionally specify an array of imagePullSecrets.
      ## Secrets must be manually created in the namespace.
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      ## e.g:
      ## pullSecrets:
      ##   - myRegistryKeySecretName
      ##
      pullSecrets: [ ]
    ## @param prometheus.jmx.resources JMX Exporter resources
    ## Resources configuration for the JMX exporter container.
    ## See the `resources` documentation above for details.
    resources: {}

## You can list load balanced service endpoint, or list of all brokers (which is hard in K8s).  e.g.:
## @param kafka.bootstrapServers list of the kafka brokers ex."PLAINTEXT://dozing-prawn-kafka-headless:9092"
kafka:
  bootstrapServers: ""

## @param schema-registry.url schema-registry url
# If the Kafka Chart is disabled a URL and port are required to connect
## e.g. gnoble-panther-schema-registry:8081
schema-registry:
  url: ""

## @param volumeMounts List of volumeMounts for connect server container
## ref: https://kubernetes.io/docs/concepts/storage/volumes/
volumeMounts:
# - name: credentials
#   mountPath: /etc/creds-volume

## @param volumes List of volumeMounts for connect server container
## ref: https://kubernetes.io/docs/concepts/storage/volumes/
volumes:
# - name: credentials
#   secret:
#     secretName: creds

## @param secrets Secret with multiple keys to serve the purpose of multiple secrets
## Values for all the keys will be base64 encoded when the Secret is created or updated
## ref: https://kubernetes.io/docs/concepts/configuration/secret/
secrets:
  # username: kafka123
  # password: connect321

## @param livenessProbe the livenessProbe for the kafka connect pods
## "livenessProbe" is required only for the edge cases where the custom script to be ran takes too much time
## and errors by the ENTRYPOINT are ignored by the container
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  # httpGet:
  #   path: /connectors
  #   port: 8083
  # initialDelaySeconds: 30
  # periodSeconds: 5
  # failureThreshold: 10

## Kafka connect pods ServiceAccount
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  ## @param serviceAccount.create Enable the creation of a ServiceAccount for Kafka connect pods
  ##
  create: true
  ## @param serviceAccount.name The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the kafka-connect.fullname template
  ##
  name: ""
  ## @param serviceAccount.annotations Annotations for Kafka connect Service Account
  ##
  annotations: {}
  ## @param serviceAccount.automountServiceAccountToken Automount API credentials for a service account.
  ##
  automountServiceAccountToken: true
