# This workflow broadly does 3 tasks-
# (1) Create/Update Release drafts
# (2) Auto Label PR's

# The update_release_draft job handles these tasks, on the basis of event which triggered workflow.
# (1) if push to master by merging PR.
# (2) if pull request opened, reopened, or synchronized (commit push)

name: Create Release Drafts

on:
  push:
    branches:
      - master
  # pull_request event is required only for auto labeler
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest

    outputs:
      tag-name: ${{ steps.release-drafter.outputs.tag_name }}

    steps:
      - id: release-drafter
        uses: release-drafter/release-drafter@v5
        with:
          commitish: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
